version: '2'
services:
    node:
        image: node:11.10.0
        working_dir: /app
        command: npm run start:debug
        volumes:
            - ./:/app:delegated
        environment:
            - NODE_ENV=development
            - PORT=8080
            - TERM=xterm-256color
        tty: true
        depends_on:
            - postgres
        ports: 
            - 8080:8080
            - 9229:9229
    nodetest:
        image: node:11.10.0
        working_dir: /app
        command: npm run start:test
        volumes:
            - ./:/app:delegated
        environment:
            - NODE_ENV=testing
            - PORT=7070
            - TERM=xterm-256color
        tty: true
        depends_on:
            - postgres
    postgres:
        image: postgres:11.1
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./library/docker/init.sql:/docker-entrypoint-initdb.d/init.sql:delegated
        ports:
            - 5432:5432
    chrome:
        image: selenium/standalone-chrome:3.141.59-dubnium