version: '2'
services:
    node:
        image: node:11.10.0
        working_dir: /app
        command: npm run start:debug
        volumes:
            - ./:/app:delegated
        environment:
            - NODE_ENV=development
            - PORT=8080
            - TERM=xterm-256color
        tty: true
        depends_on:
            - postgres
        ports: 
            - "8080:8080"
            - "9229:9229"
    nodetest:
        image: node:11.10.0
        working_dir: /app
        command: npm run start:test
        volumes:
            - ./:/app:delegated
        environment:
            - NODE_ENV=testing
            - PORT=7070
            - TERM=xterm-256color
        tty: true
        depends_on:
            - postgres
            - chrome
    chrome:
        image: selenium/standalone-chrome:3.141.59-dubnium
    postgres:
        image: postgres:11.1
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./library/docker/init.sql:/docker-entrypoint-initdb.d/init.sql:delegated
        ports:
            - "5432:5432"
    # elastic:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    #     environment:
    #         - cluster.name=docker-cluster
    #         - bootstrap.memory_lock=true
    #         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #     ulimits:
    #         memlock:
    #             soft: -1
    #             hard: -1
    #     ports:
    #         - "9200:9200"
    # elastictest:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    #     environment:
    #         - cluster.name=docker-cluster
    #         - bootstrap.memory_lock=true
    #         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #         - "discovery.zen.ping.unicast.hosts=elastic"
    #     ulimits:
    #         memlock:
    #             soft: -1
    #             hard: -1