version: '2'
services:
    postgres:
        image: postgres:11.1
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
    chrome:
        image: selenium/standalone-chrome:3.141.59-dubnium
        ports:
            - "4444:4444"