version: '2'
services:
    node:
        image: node:11.10.0
        working_dir: /app
        # Use 'npm run start-docker' to fix npm problems
        command: npm run start-debug
        volumes:
            - ./:/app:delegated
        environment:
            - NODE_ENV=development
        depends_on:
            - postgres
        ports: 
            - 8080:80
            - 9229:9229
    postgres:
        image: postgres:11.1
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:delegated
        ports:
            - 5432:5432
    chrome:
        image: selenium/standalone-chrome:3.141.59-dubnium
        ports:
            - 4444:4444